version : '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
#    restart: always
    environment:
      # root 密码
      MYSQL_ROOT_PASSWORD: 123456789
      # 初始化数据库(后续的初始化sql会在这个库执行)
      MYSQL_DATABASE: 'campus_imaotai'
    volumes:
      - /etc/localtime:/etc/localtime:ro # 设置容器时区与宿主机保持一致
      - ./mysql/data/:/var/lib/mysql/data
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ./mysql/logs:/logs
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    networks:
      - backend

  redis:
    image: redis:6.2.12
    container_name: redis
#    restart: always
    volumes:
      # 配置文件
      - ./redis/conf:/redis/config
      # 数据文件
      - ./redis/data/:/redis/data/
    command: "redis-server /redis/config/redis.conf"
    privileged: true
    ports:
      - "6379:6379"
    networks:
      - backend

  nginx-web:
    image: lxh01/campus-imaotai-web:1.0.11
    container_name: campus-imaotai-web
#    restart: always
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    privileged: true
    ports:
      - "80:80"
    depends_on:
      - mysql
      - redis
      - campus-server
    networks:
      - backend
#  nginx-web:
#    image: nginx:1.23.4
#    container_name: nginx-web
##    restart: always
#    environment:
#      # 时区上海
#      TZ: Asia/Shanghai
#    volumes:
#      # 页面目录
#      - ./nginx/html:/usr/share/nginx/html
#      # 证书映射
#      - ./nginx/cert:/etc/nginx/cert
#      # 配置文件映射
#      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
#      # 日志目录
#      - ./nginx/log:/var/log/nginx
#    privileged: true
#    ports:
#      - "80:80"
#    depends_on:
#      - mysql
#      - redis
#      - campus-server
#    networks:
#      - backend

  campus-server:
    image: oddfar/campus-imaotai:1.0.11
    container_name: campus-imaotai
#    restart: always
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      SERVER_PORT: 8160
      spring.config.additional-location: /home/campus/conf/application-prod.yml
    volumes:
      - ./server/conf:/home/campus/conf
    privileged: true
    ports:
      - "8160:8160"
    depends_on:
      - mysql
      - redis
    networks:
      - backend

networks:
  backend:
    external: true
